### ISSUE TITLE
ocrd-anybaseocr-binarize handles multiple output groups not correct

### ISSUE THREAD

**Issue by VolkerHartmann** [mjenckel/ocrd_anybaseocr#39]
ocrd-anybaseocr-binarize -m weigel/data/mets.xml -I OCR-D-IMG -O OCR-D-IMG-BIN-IMG,OCR-D-IMG-BIN -w weigel/data
create the following files:
weigel/data/OCR-D-IMG-BIN:
OCR-D-IMG-BIN_0001.png  OCR-D-IMG-BIN_0002.png  OCR-D-IMG-BIN_0003.png  OCR-D-IMG-BIN_0004.png

weigel/data/OCR-D-IMG-BIN-IMG,OCR-D-IMG-BIN:
OCR-D-IMG-BIN-IMG,OCR-D-IMG-BIN_0001.xml  OCR-D-IMG-BIN-IMG,OCR-D-IMG-BIN_0002.xml  OCR-D-IMG-BIN-IMG,OCR-D-IMG-BIN_0003.xml  OCR-D-IMG-BIN-IMG,OCR-D-IMG-BIN_0004.xml

**Comment by VolkerHartmann** [comment]
Same for deskewing but seems to be fine for cropping!?

**Comment by mahmed1995** [comment]
Fixed in 7d3fffe

**Comment by kba** [comment]
Again, you either refer to the wrong commit or 7d3fffe does not fix it.

**Comment by VolkerHartmann** [comment]
For binarization and deskewing multiple outputgroups is still buggy.
ocrd-anybaseocr-(bin/des) -i anyInput -o out1,out2 produces the following output:
out1,out2:
insgesamt 24
drwxr-xr-x  2 user user 4096 Jan 30 14:17 .
drwxrwxr-x 11 user user 4096 Jan 30 14:17 ..
-rw-r--r--  1 user user 2697 Jan 30 14:17 out1_0001.xml
-rw-r--r--  1 user user 2699 Jan 30 14:17 out1_0002.xml
-rw-r--r--  1 user user 2696 Jan 30 14:17 out1_0003.xml
-rw-r--r--  1 user user 2699 Jan 30 14:17 out1_0004.xml

out2:
insgesamt 636
drwxr-xr-x  2 user user   4096 Jan 30 14:17 .
drwxrwxr-x 11 user user   4096 Jan 30 14:17 ..
-rw-r--r--  1 user user 170291 Jan 30 14:17 out2_0001.png
-rw-r--r--  1 user user 161358 Jan 30 14:17 out2_0002.png
-rw-r--r--  1 user user 147802 Jan 30 14:17 out2_0003.png
-rw-r--r--  1 user user 152206 Jan 30 14:17 out2_0004.png

**Comment by mahmed1995** [comment]
That was wrong commit. 
This is the correct one a4c6c6ce

**Comment by VolkerHartmann** [comment]
For **binarization, deskewing and dewarping** the handling of multiple output groups is still buggy.
ocrd-anybaseocr-(bin/des) -i anyInput -o out1,out2 produces the following output:
**out1,out2:**
insgesamt 24
drwxr-xr-x 2 user user 4096 Jan 30 14:17 .
drwxrwxr-x 11 user user 4096 Jan 30 14:17 ..
-rw-r--r-- 1 user user 2697 Jan 30 14:17 out1_0001.xml

It still produces a folder with the complete string of the outputgroups **out1,out2** instead of just **out1**! 
The USE attribute of the filegroup inside mets file is correct. 

It works fine for **crop**. Why do binarize and deskewing not behave the same?

**Comment by mahmed1995** [comment]
Commit: 092183d

**Comment by VolkerHartmann** [comment]
:+1:  Works fine for binarization and deskewing.
Please fix it also for dewarping.

**Comment by mahmed1995** [comment]
Commit: 2dc4de2
Can this issue be closed now?

**Comment by VolkerHartmann** [comment]
:+1:
